name: "CodeQL Security Analysis"

on:
  push:
    branches: [ "*" ]  # Runs on any branch push
  pull_request:
    branches: [ "*" ]  # Runs on any branch pull request

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python
        queries: +security-extended,security-and-quality

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
