name: Docker Image CI

on:
  push:
    branches: [ "ac_gh_actions_testing" ]
  pull_request:
    branches: [ "ac_gh_actions_testing" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pastebin_app
