name: Docker Image CI

on:
  push:
    branches: [ "ac_gh_testing" ]
  pull_request:
    branches: [ "ac_gh_testing" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Run Docker Setup Script
      run: ./docker_setup.sh
