name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  # Replace with SHA for security

    - name: Grant execute permission for the docker setup script
      run: chmod +x ./docker_setup.sh

    - name: Run Docker Setup Script
      run: ./docker_setup.sh

    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@0.28.0 # Replace with SHA
      with:
        image-ref: 'pastebin_app'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'  # Include medium severity
        scanners: 'vuln,secret,misconfig'

    - name: Wait for Flask Application to Start
      run: |
        echo "Waiting for Flask App to be ready..."
        for i in {1..12}; do
          response=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:5000/)
          if [[ "$response" -eq 200 ]]; then
            echo "Flask app is ready."
            break
          fi
          sleep 5
        done

    - name: Test POST Request to /register End Point
      run: |
        echo "Testing Flask Application is running via POST req to /register..."
        response=$(curl -X POST http://localhost:5000/register \
          -H "Content-Type: application/json" \
          -d '{"username": "test_user", "password": "test_password"}' \
          -o /dev/null -s -w "%{http_code}")
        if [[ "$response" -ne 201 ]]; then
          echo "Flask app may not be running correctly. Endpoint returned status code $response"
          exit 1
        else
          echo "Flask app /register endpoint returned status code $response"
        fi

    # Other security checks follow as in your original script...
