name: OWASP Dependency-Check
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        uses: strategy/owasp-dependency-check-action@v4
        with:
          scan: './'
          format: 'HTML'
          fail_on_cvss: 7

      - name: Upload OWASP Dependency-Check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: './dependency-check-report.html'
