name: Run Unit Tests

on:
  push:
    branches:
      - sz_unit_tests

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Set up a database service (optional for SQLite; can be skipped)
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Set environment variables
      run: echo "API_KEY=123456789" >> $GITHUB_ENV

    - name: Run Tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        pytest

