name: DAST Fuzzing Scan
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      issues: write
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker Setup Script
        run: ./docker_setup.sh
  
      - name: Wait for Flask Application to Start
        run: |
          echo "Waiting for Flask App to be ready..."
          sleep 5
  
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:5000/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
